In [1]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()


/cjman/venv/tfda/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [52]:
import torch
import torch.nn as nn

a = torch.tensor([1.], requires_grad=True)
b = torch.tensor([2.], requires_grad=True)
c = torch.tensor([3.], requires_grad=True)
w = nn.Linear(1, 1, bias=False)
x = nn.Linear(1, 1, bias=False)
d = w(a)
d = x(d)
d.backward()
print(w.weight.grad)
print(x.weight.grad)
x.requires_grad_(False) # requires_grad를 false로 해도 이전 레이어의 gradient를 구하는데 영향을 주진않는다.
e = w(b)
e = x(e)
e.backward()
print(w.weight.grad)
print(x.weight.grad)


tensor([[0.4268]])
tensor([[-0.5787]])
tensor([[1.2804]])
tensor([[-0.5787]])


In [51]:
import torch
import torch.nn as nn

a = torch.tensor([1.], requires_grad=True)
b = torch.tensor([2.], requires_grad=True)
c = torch.tensor([3.], requires_grad=True)
w = nn.Linear(1, 1, bias=False)
x = nn.Linear(1, 1, bias=False)
d = w(a)
d = x(d)
d.backward()
print(w.weight.grad)
print(x.weight.grad)
e = w(b)
print(id(e))
with torch.no_grad(): # 이렇게하면 output e가 requires_grad가 false가 되니깐 backward를 실행할 수가없음.
    print(id(e))
    
    e = x(e)
    print(id(e))

    print(e.requires_grad)
    
e.backward()
print(w.weight.grad)
print(x.weight.grad)


tensor([[0.3706]])
tensor([[0.5833]])
140582953813184
140582953813184
140582953685632
False
tensor([[0.3706]])
tensor([[0.5833]])


In [6]:
import torch
import torch.nn as nn

c = torch.tensor([3.], requires_grad=True)
w1 = nn.Linear(1, 1, bias=False)
w2 = nn.Linear(1, 1, bias=False)

a = w1(c)
a = w2(a)
a.backward()
w2.zero_grad()

print(w1.weight.grad)
print(w2.weight.grad)
# 이렇게해도 grad가 none은 아니다.. 그냥 0이나 none이면 문제가 되는건가?

tensor([[-0.3710]])
tensor([[0.]])
